"""
Playwright E2E Test Template with [REQ-xxx] traceability.

Every test references the requirement it verifies.
The /critic command uses this pattern to auto-generate tests for failures.

Setup: uv add playwright pytest-playwright && uv run playwright install chromium
Run:   uv run pytest tests/e2e/ -v
"""

import re

from playwright.sync_api import Page, expect


# --- Page Map (generated by /critic Step 1) ---

PAGES = {
    "landing": "/",
    "login": "/login/",
    "register": "/register/",
    "dashboard": "/",  # after login
    "workflows": "/workflows/",
    "documents": "/documents/",
    "staff": "/staff/",
    "search": "/search/",
    "chat": "/chat/",
}


# --- Helpers ---


def login(page: Page, base_url: str, email: str, password: str):
    """Login helper — reused across all authenticated tests."""
    page.goto(f"{base_url}/login/")
    page.fill('input[name="email"]', email)
    page.fill('input[name="password"]', password)
    page.click('button[type="submit"]')
    page.wait_for_url(f"{base_url}/**/")


# --- DEPTH TESTS (vertical — follow one path to its end) ---


class TestLoginToWorkflowDepth:
    """Depth test: Landing → Login → Dashboard → Workflows → Tasks."""

    def test_full_user_journey(self, page: Page, base_url: str):  # [REQ-001] [REQ-002]
        """Complete journey from login to task management."""
        # Landing page loads
        page.goto(base_url)
        expect(page).to_have_title(re.compile(".*"))

        # Navigate to login
        page.click("text=Login")
        expect(page).to_have_url(re.compile(".*/login/"))

        # Login
        login(page, base_url, "admin@clinic.localhost", "admin123")

        # Dashboard loads with stats
        expect(page.locator("h1")).to_contain_text("Dashboard")

        # Navigate to workflows
        page.click("text=Workflows")
        expect(page).to_have_url(re.compile(".*/workflows/"))

        # Workflows list visible
        expect(page.locator("article")).to_have_count_greater_than(0)


# --- BREADTH TESTS (horizontal — test all options at one level) ---


class TestDashboardBreadth:
    """Breadth test: all navigation options from dashboard."""

    def test_nav_workflows(self, page: Page, base_url: str):  # [REQ-001]
        login(page, base_url, "admin@clinic.localhost", "admin123")
        page.click("text=Workflows")
        expect(page).to_have_url(re.compile(".*/workflows/"))

    def test_nav_documents(self, page: Page, base_url: str):  # [REQ-003]
        login(page, base_url, "admin@clinic.localhost", "admin123")
        page.click("text=Documents")
        expect(page).to_have_url(re.compile(".*/documents/"))

    def test_nav_staff(self, page: Page, base_url: str):  # [REQ-004]
        login(page, base_url, "admin@clinic.localhost", "admin123")
        page.click("text=Staff")
        expect(page).to_have_url(re.compile(".*/staff/"))


# --- EDGE TESTS (what breaks) ---


class TestEdgeCases:
    """Edge cases that /critic specifically checks."""

    def test_login_wrong_password(self, page: Page, base_url: str):  # [REQ-005]
        """Wrong password shows error, doesn't crash."""
        page.goto(f"{base_url}/login/")
        page.fill('input[name="email"]', "admin@clinic.localhost")
        page.fill('input[name="password"]', "wrongpassword")
        page.click('button[type="submit"]')
        # Should show error message, not crash
        expect(page.locator(".error, [role='alert'], .alert")).to_be_visible()

    def test_empty_state(self, page: Page, base_url: str):  # [REQ-006]
        """Empty data shows helpful message, not 'Loading...' forever."""
        login(page, base_url, "admin@clinic.localhost", "admin123")
        page.goto(f"{base_url}/workflows/")
        # Should show "No workflows" or similar, not infinite loading
        page.wait_for_timeout(3000)
        content = page.content()
        assert "Loading" not in content or "No " in content

    def test_xss_prevention(self, page: Page, base_url: str):  # [REQ-007]
        """XSS in form fields is sanitized."""
        login(page, base_url, "admin@clinic.localhost", "admin123")
        page.goto(f"{base_url}/workflows/")
        # Try to inject script via form
        xss_payload = '<script>alert("xss")</script>'
        page.fill('input[name="name"]', xss_payload)
        page.click('button[type="submit"]')
        # Script tag should not execute — check it's escaped
        content = page.content()
        assert "<script>alert" not in content

    def test_unauthorized_redirect(self, page: Page, base_url: str):  # [REQ-008]
        """Unauthenticated user redirected to login."""
        page.goto(f"{base_url}/workflows/")
        expect(page).to_have_url(re.compile(".*/login/"))


# --- AUTH TESTS (role-based access) ---


class TestRoleAccess:
    """Verify role-based access control on frontend."""

    def test_admin_sees_staff_page(self, page: Page, base_url: str):  # [REQ-009]
        login(page, base_url, "admin@clinic.localhost", "admin123")
        page.goto(f"{base_url}/staff/")
        expect(page.locator("h1")).to_contain_text("Staff")

    def test_staff_cannot_see_admin_features(self, page: Page, base_url: str):  # [REQ-010]
        login(page, base_url, "staff@clinic.localhost", "staff123")
        # Staff should not see invite button or transition buttons
        page.goto(f"{base_url}/staff/")
        invite_btn = page.locator("text=Invite")
        expect(invite_btn).to_have_count(0)


# --- conftest.py content ---
# Put this in tests/e2e/conftest.py:
#
# import pytest
#
# @pytest.fixture(scope="session")
# def base_url():
#     return "http://localhost:8000"
